# Generated by Django 5.0.3 on 2024-04-30 14:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_image),
        ),
    ]
